{{- if .Values.front.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front
  namespace: {{ .Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: {{ .Values.certManager.clusterIssuer | quote }}
spec:
  tls:
    - hosts:
        - {{ .Values.front.ingress.host }}
      secretName: front-tls
  rules:
    - host: {{ .Values.front.ingress.host }}
      http:
        paths:
          - path: {{ .Values.front.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: front
                port:
                  number: {{ .Values.front.service.port }}
{{- end }}
