{{- if .Values.front.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front
  namespace: {{ .Values.namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: front
spec:
  ingressClassName: {{ .Values.front.ingress.className }}
  rules:
    - host: {{ .Values.front.ingress.host }}
      http:
        paths:
          - path: {{ .Values.front.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: front
                port:
                  number: {{ .Values.front.service.port }}
  {{- if .Values.front.ingress.tls }}
  tls:
    {{- toYaml .Values.front.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
