apiVersion: v1
kind: Service
metadata:
  name: front
  namespace: {{ .Values.namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: front
spec:
  type: {{ .Values.front.service.type }}
  selector:
    app.kubernetes.io/name: front
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.front.service.port }}
      targetPort: {{ .Values.front.port }}
