apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: {{ .Values.namespace }}
  annotations:
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-options: Replace=false
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: {{ .Values.mongodb.storage.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.mongodb.storage.size }}
