apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  # Les valeurs sont encodées en base64 au moment du templating Helm
  mongodb-username: {{ .Values.mongodb.auth.username | b64enc | quote }}
  mongodb-password: {{ .Values.mongodb.auth.password | b64enc | quote }}
