apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - name: mongo
      port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.port }}
