{{- if .Values.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  namespace: {{ .Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: {{ .Values.certManager.clusterIssuer | quote }}
spec:
  tls:
    - hosts:
        - {{ printf "api.%s.nip.io" .Values.serverIp }}
      secretName: api-tls
  rules:
    - host: {{ printf "api.%s.nip.io" .Values.serverIp }}
      http:
        paths:
          - path: {{ .Values.api.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: {{ .Values.api.service.port }}
{{- end }}
