{{- if .Values.api.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  namespace: {{ .Values.namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: {{ .Values.api.ingress.className }}
  rules:
    - host: {{ .Values.api.ingress.host }}
      http:
        paths:
          - path: {{ .Values.api.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: {{ .Values.api.service.port }}
  {{- if .Values.api.ingress.tls }}
  tls:
    {{- toYaml .Values.api.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
